# Generated by Django 2.1.4 on 2018-12-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
    ]
